/** Curated study roadmaps, tracked as checklists with local progress. */

export interface RoadmapProblem {
  title: string
  slug: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  group: string
  /** Optional explicit URL (for non-LeetCode problems, e.g. GeeksforGeeks). */
  url?: string
}

/** Direct link to solve a problem (LeetCode by default). */
export function problemUrl(p: RoadmapProblem): string {
  return p.url ?? `https://leetcode.com/problems/${p.slug}/`
}

const BLIND_75: RoadmapProblem[] = [
  // Array
  { group: 'Array', title: 'Two Sum', slug: 'two-sum', difficulty: 'Easy' },
  { group: 'Array', title: 'Best Time to Buy and Sell Stock', slug: 'best-time-to-buy-and-sell-stock', difficulty: 'Easy' },
  { group: 'Array', title: 'Contains Duplicate', slug: 'contains-duplicate', difficulty: 'Easy' },
  { group: 'Array', title: 'Product of Array Except Self', slug: 'product-of-array-except-self', difficulty: 'Medium' },
  { group: 'Array', title: 'Maximum Subarray', slug: 'maximum-subarray', difficulty: 'Medium' },
  { group: 'Array', title: 'Maximum Product Subarray', slug: 'maximum-product-subarray', difficulty: 'Medium' },
  { group: 'Array', title: 'Find Minimum in Rotated Sorted Array', slug: 'find-minimum-in-rotated-sorted-array', difficulty: 'Medium' },
  { group: 'Array', title: 'Search in Rotated Sorted Array', slug: 'search-in-rotated-sorted-array', difficulty: 'Medium' },
  { group: 'Array', title: '3Sum', slug: '3sum', difficulty: 'Medium' },
  { group: 'Array', title: 'Container With Most Water', slug: 'container-with-most-water', difficulty: 'Medium' },
  // Binary
  { group: 'Binary', title: 'Sum of Two Integers', slug: 'sum-of-two-integers', difficulty: 'Medium' },
  { group: 'Binary', title: 'Number of 1 Bits', slug: 'number-of-1-bits', difficulty: 'Easy' },
  { group: 'Binary', title: 'Counting Bits', slug: 'counting-bits', difficulty: 'Easy' },
  { group: 'Binary', title: 'Missing Number', slug: 'missing-number', difficulty: 'Easy' },
  { group: 'Binary', title: 'Reverse Bits', slug: 'reverse-bits', difficulty: 'Easy' },
  // Dynamic Programming
  { group: 'Dynamic Programming', title: 'Climbing Stairs', slug: 'climbing-stairs', difficulty: 'Easy' },
  { group: 'Dynamic Programming', title: 'Coin Change', slug: 'coin-change', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'Longest Increasing Subsequence', slug: 'longest-increasing-subsequence', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'Longest Common Subsequence', slug: 'longest-common-subsequence', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'Word Break', slug: 'word-break', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'Combination Sum IV', slug: 'combination-sum-iv', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'House Robber', slug: 'house-robber', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'House Robber II', slug: 'house-robber-ii', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'Decode Ways', slug: 'decode-ways', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'Unique Paths', slug: 'unique-paths', difficulty: 'Medium' },
  { group: 'Dynamic Programming', title: 'Jump Game', slug: 'jump-game', difficulty: 'Medium' },
  // Graph
  { group: 'Graph', title: 'Clone Graph', slug: 'clone-graph', difficulty: 'Medium' },
  { group: 'Graph', title: 'Course Schedule', slug: 'course-schedule', difficulty: 'Medium' },
  { group: 'Graph', title: 'Pacific Atlantic Water Flow', slug: 'pacific-atlantic-water-flow', difficulty: 'Medium' },
  { group: 'Graph', title: 'Number of Islands', slug: 'number-of-islands', difficulty: 'Medium' },
  { group: 'Graph', title: 'Longest Consecutive Sequence', slug: 'longest-consecutive-sequence', difficulty: 'Medium' },
  { group: 'Graph', title: 'Alien Dictionary', slug: 'alien-dictionary', difficulty: 'Hard' },
  { group: 'Graph', title: 'Graph Valid Tree', slug: 'graph-valid-tree', difficulty: 'Medium' },
  { group: 'Graph', title: 'Number of Connected Components', slug: 'number-of-connected-components-in-an-undirected-graph', difficulty: 'Medium' },
  // Interval
  { group: 'Interval', title: 'Insert Interval', slug: 'insert-interval', difficulty: 'Medium' },
  { group: 'Interval', title: 'Merge Intervals', slug: 'merge-intervals', difficulty: 'Medium' },
  { group: 'Interval', title: 'Non-overlapping Intervals', slug: 'non-overlapping-intervals', difficulty: 'Medium' },
  { group: 'Interval', title: 'Meeting Rooms', slug: 'meeting-rooms', difficulty: 'Easy' },
  { group: 'Interval', title: 'Meeting Rooms II', slug: 'meeting-rooms-ii', difficulty: 'Medium' },
  // Linked List
  { group: 'Linked List', title: 'Reverse Linked List', slug: 'reverse-linked-list', difficulty: 'Easy' },
  { group: 'Linked List', title: 'Linked List Cycle', slug: 'linked-list-cycle', difficulty: 'Easy' },
  { group: 'Linked List', title: 'Merge Two Sorted Lists', slug: 'merge-two-sorted-lists', difficulty: 'Easy' },
  { group: 'Linked List', title: 'Merge k Sorted Lists', slug: 'merge-k-sorted-lists', difficulty: 'Hard' },
  { group: 'Linked List', title: 'Remove Nth Node From End of List', slug: 'remove-nth-node-from-end-of-list', difficulty: 'Medium' },
  { group: 'Linked List', title: 'Reorder List', slug: 'reorder-list', difficulty: 'Medium' },
  // Matrix
  { group: 'Matrix', title: 'Set Matrix Zeroes', slug: 'set-matrix-zeroes', difficulty: 'Medium' },
  { group: 'Matrix', title: 'Spiral Matrix', slug: 'spiral-matrix', difficulty: 'Medium' },
  { group: 'Matrix', title: 'Rotate Image', slug: 'rotate-image', difficulty: 'Medium' },
  { group: 'Matrix', title: 'Word Search', slug: 'word-search', difficulty: 'Medium' },
  // String
  { group: 'String', title: 'Longest Substring Without Repeating Characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'Medium' },
  { group: 'String', title: 'Longest Repeating Character Replacement', slug: 'longest-repeating-character-replacement', difficulty: 'Medium' },
  { group: 'String', title: 'Minimum Window Substring', slug: 'minimum-window-substring', difficulty: 'Hard' },
  { group: 'String', title: 'Valid Anagram', slug: 'valid-anagram', difficulty: 'Easy' },
  { group: 'String', title: 'Group Anagrams', slug: 'group-anagrams', difficulty: 'Medium' },
  { group: 'String', title: 'Valid Parentheses', slug: 'valid-parentheses', difficulty: 'Easy' },
  { group: 'String', title: 'Valid Palindrome', slug: 'valid-palindrome', difficulty: 'Easy' },
  { group: 'String', title: 'Longest Palindromic Substring', slug: 'longest-palindromic-substring', difficulty: 'Medium' },
  { group: 'String', title: 'Palindromic Substrings', slug: 'palindromic-substrings', difficulty: 'Medium' },
  { group: 'String', title: 'Encode and Decode Strings', slug: 'encode-and-decode-strings', difficulty: 'Medium' },
  // Tree
  { group: 'Tree', title: 'Maximum Depth of Binary Tree', slug: 'maximum-depth-of-binary-tree', difficulty: 'Easy' },
  { group: 'Tree', title: 'Same Tree', slug: 'same-tree', difficulty: 'Easy' },
  { group: 'Tree', title: 'Invert Binary Tree', slug: 'invert-binary-tree', difficulty: 'Easy' },
  { group: 'Tree', title: 'Binary Tree Maximum Path Sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'Hard' },
  { group: 'Tree', title: 'Binary Tree Level Order Traversal', slug: 'binary-tree-level-order-traversal', difficulty: 'Medium' },
  { group: 'Tree', title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-and-deserialize-binary-tree', difficulty: 'Hard' },
  { group: 'Tree', title: 'Subtree of Another Tree', slug: 'subtree-of-another-tree', difficulty: 'Easy' },
  { group: 'Tree', title: 'Construct Binary Tree from Preorder and Inorder', slug: 'construct-binary-tree-from-preorder-and-inorder-traversal', difficulty: 'Medium' },
  { group: 'Tree', title: 'Validate Binary Search Tree', slug: 'validate-binary-search-tree', difficulty: 'Medium' },
  { group: 'Tree', title: 'Kth Smallest Element in a BST', slug: 'kth-smallest-element-in-a-bst', difficulty: 'Medium' },
  { group: 'Tree', title: 'Lowest Common Ancestor of a BST', slug: 'lowest-common-ancestor-of-a-binary-search-tree', difficulty: 'Medium' },
  { group: 'Tree', title: 'Implement Trie (Prefix Tree)', slug: 'implement-trie-prefix-tree', difficulty: 'Medium' },
  { group: 'Tree', title: 'Add and Search Word', slug: 'design-add-and-search-words-data-structure', difficulty: 'Medium' },
  { group: 'Tree', title: 'Word Search II', slug: 'word-search-ii', difficulty: 'Hard' },
  // Heap
  { group: 'Heap', title: 'Top K Frequent Elements', slug: 'top-k-frequent-elements', difficulty: 'Medium' },
  { group: 'Heap', title: 'Find Median from Data Stream', slug: 'find-median-from-data-stream', difficulty: 'Hard' },
]

const N = (
  group: string,
  title: string,
  slug: string,
  difficulty: 'Easy' | 'Medium' | 'Hard',
): RoadmapProblem => ({ group, title, slug, difficulty })

const NEETCODE_150: RoadmapProblem[] = [
  N('Arrays & Hashing', 'Contains Duplicate', 'contains-duplicate', 'Easy'),
  N('Arrays & Hashing', 'Valid Anagram', 'valid-anagram', 'Easy'),
  N('Arrays & Hashing', 'Two Sum', 'two-sum', 'Easy'),
  N('Arrays & Hashing', 'Group Anagrams', 'group-anagrams', 'Medium'),
  N('Arrays & Hashing', 'Top K Frequent Elements', 'top-k-frequent-elements', 'Medium'),
  N('Arrays & Hashing', 'Product of Array Except Self', 'product-of-array-except-self', 'Medium'),
  N('Arrays & Hashing', 'Valid Sudoku', 'valid-sudoku', 'Medium'),
  N('Arrays & Hashing', 'Encode and Decode Strings', 'encode-and-decode-strings', 'Medium'),
  N('Arrays & Hashing', 'Longest Consecutive Sequence', 'longest-consecutive-sequence', 'Medium'),
  N('Two Pointers', 'Valid Palindrome', 'valid-palindrome', 'Easy'),
  N('Two Pointers', 'Two Sum II', 'two-sum-ii-input-array-is-sorted', 'Medium'),
  N('Two Pointers', '3Sum', '3sum', 'Medium'),
  N('Two Pointers', 'Container With Most Water', 'container-with-most-water', 'Medium'),
  N('Two Pointers', 'Trapping Rain Water', 'trapping-rain-water', 'Hard'),
  N('Sliding Window', 'Best Time to Buy and Sell Stock', 'best-time-to-buy-and-sell-stock', 'Easy'),
  N('Sliding Window', 'Longest Substring Without Repeating Characters', 'longest-substring-without-repeating-characters', 'Medium'),
  N('Sliding Window', 'Longest Repeating Character Replacement', 'longest-repeating-character-replacement', 'Medium'),
  N('Sliding Window', 'Permutation in String', 'permutation-in-string', 'Medium'),
  N('Sliding Window', 'Minimum Window Substring', 'minimum-window-substring', 'Hard'),
  N('Sliding Window', 'Sliding Window Maximum', 'sliding-window-maximum', 'Hard'),
  N('Stack', 'Valid Parentheses', 'valid-parentheses', 'Easy'),
  N('Stack', 'Min Stack', 'min-stack', 'Medium'),
  N('Stack', 'Evaluate Reverse Polish Notation', 'evaluate-reverse-polish-notation', 'Medium'),
  N('Stack', 'Generate Parentheses', 'generate-parentheses', 'Medium'),
  N('Stack', 'Daily Temperatures', 'daily-temperatures', 'Medium'),
  N('Stack', 'Car Fleet', 'car-fleet', 'Medium'),
  N('Stack', 'Largest Rectangle in Histogram', 'largest-rectangle-in-histogram', 'Hard'),
  N('Binary Search', 'Binary Search', 'binary-search', 'Easy'),
  N('Binary Search', 'Search a 2D Matrix', 'search-a-2d-matrix', 'Medium'),
  N('Binary Search', 'Koko Eating Bananas', 'koko-eating-bananas', 'Medium'),
  N('Binary Search', 'Find Minimum in Rotated Sorted Array', 'find-minimum-in-rotated-sorted-array', 'Medium'),
  N('Binary Search', 'Search in Rotated Sorted Array', 'search-in-rotated-sorted-array', 'Medium'),
  N('Binary Search', 'Time Based Key-Value Store', 'time-based-key-value-store', 'Medium'),
  N('Binary Search', 'Median of Two Sorted Arrays', 'median-of-two-sorted-arrays', 'Hard'),
  N('Linked List', 'Reverse Linked List', 'reverse-linked-list', 'Easy'),
  N('Linked List', 'Merge Two Sorted Lists', 'merge-two-sorted-lists', 'Easy'),
  N('Linked List', 'Reorder List', 'reorder-list', 'Medium'),
  N('Linked List', 'Remove Nth Node From End of List', 'remove-nth-node-from-end-of-list', 'Medium'),
  N('Linked List', 'Copy List with Random Pointer', 'copy-list-with-random-pointer', 'Medium'),
  N('Linked List', 'Add Two Numbers', 'add-two-numbers', 'Medium'),
  N('Linked List', 'Linked List Cycle', 'linked-list-cycle', 'Easy'),
  N('Linked List', 'Find the Duplicate Number', 'find-the-duplicate-number', 'Medium'),
  N('Linked List', 'LRU Cache', 'lru-cache', 'Medium'),
  N('Linked List', 'Merge k Sorted Lists', 'merge-k-sorted-lists', 'Hard'),
  N('Linked List', 'Reverse Nodes in k-Group', 'reverse-nodes-in-k-group', 'Hard'),
  N('Trees', 'Invert Binary Tree', 'invert-binary-tree', 'Easy'),
  N('Trees', 'Maximum Depth of Binary Tree', 'maximum-depth-of-binary-tree', 'Easy'),
  N('Trees', 'Diameter of Binary Tree', 'diameter-of-binary-tree', 'Easy'),
  N('Trees', 'Balanced Binary Tree', 'balanced-binary-tree', 'Easy'),
  N('Trees', 'Same Tree', 'same-tree', 'Easy'),
  N('Trees', 'Subtree of Another Tree', 'subtree-of-another-tree', 'Easy'),
  N('Trees', 'Lowest Common Ancestor of a BST', 'lowest-common-ancestor-of-a-binary-search-tree', 'Medium'),
  N('Trees', 'Binary Tree Level Order Traversal', 'binary-tree-level-order-traversal', 'Medium'),
  N('Trees', 'Binary Tree Right Side View', 'binary-tree-right-side-view', 'Medium'),
  N('Trees', 'Count Good Nodes in Binary Tree', 'count-good-nodes-in-binary-tree', 'Medium'),
  N('Trees', 'Validate Binary Search Tree', 'validate-binary-search-tree', 'Medium'),
  N('Trees', 'Kth Smallest Element in a BST', 'kth-smallest-element-in-a-bst', 'Medium'),
  N('Trees', 'Construct Binary Tree from Preorder and Inorder', 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Medium'),
  N('Trees', 'Binary Tree Maximum Path Sum', 'binary-tree-maximum-path-sum', 'Hard'),
  N('Trees', 'Serialize and Deserialize Binary Tree', 'serialize-and-deserialize-binary-tree', 'Hard'),
  N('Tries', 'Implement Trie (Prefix Tree)', 'implement-trie-prefix-tree', 'Medium'),
  N('Tries', 'Design Add and Search Words', 'design-add-and-search-words-data-structure', 'Medium'),
  N('Tries', 'Word Search II', 'word-search-ii', 'Hard'),
  N('Heap / Priority Queue', 'Kth Largest Element in a Stream', 'kth-largest-element-in-a-stream', 'Easy'),
  N('Heap / Priority Queue', 'Last Stone Weight', 'last-stone-weight', 'Easy'),
  N('Heap / Priority Queue', 'K Closest Points to Origin', 'k-closest-points-to-origin', 'Medium'),
  N('Heap / Priority Queue', 'Kth Largest Element in an Array', 'kth-largest-element-in-an-array', 'Medium'),
  N('Heap / Priority Queue', 'Task Scheduler', 'task-scheduler', 'Medium'),
  N('Heap / Priority Queue', 'Design Twitter', 'design-twitter', 'Medium'),
  N('Heap / Priority Queue', 'Find Median from Data Stream', 'find-median-from-data-stream', 'Hard'),
  N('Backtracking', 'Subsets', 'subsets', 'Medium'),
  N('Backtracking', 'Combination Sum', 'combination-sum', 'Medium'),
  N('Backtracking', 'Permutations', 'permutations', 'Medium'),
  N('Backtracking', 'Subsets II', 'subsets-ii', 'Medium'),
  N('Backtracking', 'Combination Sum II', 'combination-sum-ii', 'Medium'),
  N('Backtracking', 'Word Search', 'word-search', 'Medium'),
  N('Backtracking', 'Palindrome Partitioning', 'palindrome-partitioning', 'Medium'),
  N('Backtracking', 'Letter Combinations of a Phone Number', 'letter-combinations-of-a-phone-number', 'Medium'),
  N('Backtracking', 'N-Queens', 'n-queens', 'Hard'),
  N('Graphs', 'Number of Islands', 'number-of-islands', 'Medium'),
  N('Graphs', 'Max Area of Island', 'max-area-of-island', 'Medium'),
  N('Graphs', 'Clone Graph', 'clone-graph', 'Medium'),
  N('Graphs', 'Walls and Gates', 'walls-and-gates', 'Medium'),
  N('Graphs', 'Rotting Oranges', 'rotting-oranges', 'Medium'),
  N('Graphs', 'Pacific Atlantic Water Flow', 'pacific-atlantic-water-flow', 'Medium'),
  N('Graphs', 'Surrounded Regions', 'surrounded-regions', 'Medium'),
  N('Graphs', 'Course Schedule', 'course-schedule', 'Medium'),
  N('Graphs', 'Course Schedule II', 'course-schedule-ii', 'Medium'),
  N('Graphs', 'Graph Valid Tree', 'graph-valid-tree', 'Medium'),
  N('Graphs', 'Number of Connected Components', 'number-of-connected-components-in-an-undirected-graph', 'Medium'),
  N('Graphs', 'Redundant Connection', 'redundant-connection', 'Medium'),
  N('Graphs', 'Word Ladder', 'word-ladder', 'Hard'),
  N('Advanced Graphs', 'Reconstruct Itinerary', 'reconstruct-itinerary', 'Hard'),
  N('Advanced Graphs', 'Min Cost to Connect All Points', 'min-cost-to-connect-all-points', 'Medium'),
  N('Advanced Graphs', 'Network Delay Time', 'network-delay-time', 'Medium'),
  N('Advanced Graphs', 'Swim in Rising Water', 'swim-in-rising-water', 'Hard'),
  N('Advanced Graphs', 'Alien Dictionary', 'alien-dictionary', 'Hard'),
  N('Advanced Graphs', 'Cheapest Flights Within K Stops', 'cheapest-flights-within-k-stops', 'Medium'),
  N('1-D DP', 'Climbing Stairs', 'climbing-stairs', 'Easy'),
  N('1-D DP', 'Min Cost Climbing Stairs', 'min-cost-climbing-stairs', 'Easy'),
  N('1-D DP', 'House Robber', 'house-robber', 'Medium'),
  N('1-D DP', 'House Robber II', 'house-robber-ii', 'Medium'),
  N('1-D DP', 'Longest Palindromic Substring', 'longest-palindromic-substring', 'Medium'),
  N('1-D DP', 'Palindromic Substrings', 'palindromic-substrings', 'Medium'),
  N('1-D DP', 'Decode Ways', 'decode-ways', 'Medium'),
  N('1-D DP', 'Coin Change', 'coin-change', 'Medium'),
  N('1-D DP', 'Maximum Product Subarray', 'maximum-product-subarray', 'Medium'),
  N('1-D DP', 'Word Break', 'word-break', 'Medium'),
  N('1-D DP', 'Longest Increasing Subsequence', 'longest-increasing-subsequence', 'Medium'),
  N('1-D DP', 'Partition Equal Subset Sum', 'partition-equal-subset-sum', 'Medium'),
  N('2-D DP', 'Unique Paths', 'unique-paths', 'Medium'),
  N('2-D DP', 'Longest Common Subsequence', 'longest-common-subsequence', 'Medium'),
  N('2-D DP', 'Best Time to Buy/Sell Stock with Cooldown', 'best-time-to-buy-and-sell-stock-with-cooldown', 'Medium'),
  N('2-D DP', 'Coin Change II', 'coin-change-ii', 'Medium'),
  N('2-D DP', 'Target Sum', 'target-sum', 'Medium'),
  N('2-D DP', 'Interleaving String', 'interleaving-string', 'Medium'),
  N('2-D DP', 'Longest Increasing Path in a Matrix', 'longest-increasing-path-in-a-matrix', 'Hard'),
  N('2-D DP', 'Distinct Subsequences', 'distinct-subsequences', 'Hard'),
  N('2-D DP', 'Edit Distance', 'edit-distance', 'Medium'),
  N('2-D DP', 'Burst Balloons', 'burst-balloons', 'Hard'),
  N('2-D DP', 'Regular Expression Matching', 'regular-expression-matching', 'Hard'),
  N('Greedy', 'Maximum Subarray', 'maximum-subarray', 'Medium'),
  N('Greedy', 'Jump Game', 'jump-game', 'Medium'),
  N('Greedy', 'Jump Game II', 'jump-game-ii', 'Medium'),
  N('Greedy', 'Gas Station', 'gas-station', 'Medium'),
  N('Greedy', 'Hand of Straights', 'hand-of-straights', 'Medium'),
  N('Greedy', 'Merge Triplets to Form Target Triplet', 'merge-triplets-to-form-target-triplet', 'Medium'),
  N('Greedy', 'Partition Labels', 'partition-labels', 'Medium'),
  N('Greedy', 'Valid Parenthesis String', 'valid-parenthesis-string', 'Medium'),
  N('Intervals', 'Insert Interval', 'insert-interval', 'Medium'),
  N('Intervals', 'Merge Intervals', 'merge-intervals', 'Medium'),
  N('Intervals', 'Non-overlapping Intervals', 'non-overlapping-intervals', 'Medium'),
  N('Intervals', 'Meeting Rooms', 'meeting-rooms', 'Easy'),
  N('Intervals', 'Meeting Rooms II', 'meeting-rooms-ii', 'Medium'),
  N('Intervals', 'Minimum Interval to Include Each Query', 'minimum-interval-to-include-each-query', 'Hard'),
  N('Math & Geometry', 'Rotate Image', 'rotate-image', 'Medium'),
  N('Math & Geometry', 'Spiral Matrix', 'spiral-matrix', 'Medium'),
  N('Math & Geometry', 'Set Matrix Zeroes', 'set-matrix-zeroes', 'Medium'),
  N('Math & Geometry', 'Happy Number', 'happy-number', 'Easy'),
  N('Math & Geometry', 'Plus One', 'plus-one', 'Easy'),
  N('Math & Geometry', 'Pow(x, n)', 'powx-n', 'Medium'),
  N('Math & Geometry', 'Multiply Strings', 'multiply-strings', 'Medium'),
  N('Math & Geometry', 'Detect Squares', 'detect-squares', 'Medium'),
  N('Bit Manipulation', 'Single Number', 'single-number', 'Easy'),
  N('Bit Manipulation', 'Number of 1 Bits', 'number-of-1-bits', 'Easy'),
  N('Bit Manipulation', 'Counting Bits', 'counting-bits', 'Easy'),
  N('Bit Manipulation', 'Reverse Bits', 'reverse-bits', 'Easy'),
  N('Bit Manipulation', 'Missing Number', 'missing-number', 'Easy'),
  N('Bit Manipulation', 'Sum of Two Integers', 'sum-of-two-integers', 'Medium'),
  N('Bit Manipulation', 'Reverse Integer', 'reverse-integer', 'Medium'),
]

const GRIND_75: RoadmapProblem[] = [
  { group: "Array", title: "Two Sum", slug: "two-sum", difficulty: "Easy" },
  { group: "Stack", title: "Valid Parentheses", slug: "valid-parentheses", difficulty: "Easy" },
  { group: "Linked List", title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists", difficulty: "Easy" },
  { group: "Array", title: "Best Time to Buy and Sell Stock", slug: "best-time-to-buy-and-sell-stock", difficulty: "Easy" },
  { group: "String", title: "Valid Palindrome", slug: "valid-palindrome", difficulty: "Easy" },
  { group: "Tree", title: "Invert Binary Tree", slug: "invert-binary-tree", difficulty: "Easy" },
  { group: "String", title: "Valid Anagram", slug: "valid-anagram", difficulty: "Easy" },
  { group: "Binary Search", title: "Binary Search", slug: "binary-search", difficulty: "Easy" },
  { group: "Graph", title: "Flood Fill", slug: "flood-fill", difficulty: "Easy" },
  { group: "Tree", title: "Lowest Common Ancestor of a Binary Search Tree", slug: "lowest-common-ancestor-of-a-binary-search-tree", difficulty: "Medium" },
  { group: "Tree", title: "Balanced Binary Tree", slug: "balanced-binary-tree", difficulty: "Easy" },
  { group: "Linked List", title: "Linked List Cycle", slug: "linked-list-cycle", difficulty: "Easy" },
  { group: "Stack", title: "Implement Queue using Stacks", slug: "implement-queue-using-stacks", difficulty: "Easy" },
  { group: "Binary Search", title: "First Bad Version", slug: "first-bad-version", difficulty: "Easy" },
  { group: "Hash Table", title: "Ransom Note", slug: "ransom-note", difficulty: "Easy" },
  { group: "Dynamic Programming", title: "Climbing Stairs", slug: "climbing-stairs", difficulty: "Easy" },
  { group: "String", title: "Longest Palindrome", slug: "longest-palindrome", difficulty: "Easy" },
  { group: "Linked List", title: "Reverse Linked List", slug: "reverse-linked-list", difficulty: "Easy" },
  { group: "Array", title: "Majority Element", slug: "majority-element", difficulty: "Easy" },
  { group: "Math", title: "Add Binary", slug: "add-binary", difficulty: "Easy" },
  { group: "Tree", title: "Diameter of Binary Tree", slug: "diameter-of-binary-tree", difficulty: "Easy" },
  { group: "Linked List", title: "Middle of the Linked List", slug: "middle-of-the-linked-list", difficulty: "Easy" },
  { group: "Tree", title: "Maximum Depth of Binary Tree", slug: "maximum-depth-of-binary-tree", difficulty: "Easy" },
  { group: "Array", title: "Contains Duplicate", slug: "contains-duplicate", difficulty: "Easy" },
  { group: "Dynamic Programming", title: "Maximum Subarray", slug: "maximum-subarray", difficulty: "Medium" },
  { group: "Interval", title: "Insert Interval", slug: "insert-interval", difficulty: "Medium" },
  { group: "Graph", title: "01 Matrix", slug: "01-matrix", difficulty: "Medium" },
  { group: "Heap", title: "K Closest Points to Origin", slug: "k-closest-points-to-origin", difficulty: "Medium" },
  { group: "Sliding Window", title: "Longest Substring Without Repeating Characters", slug: "longest-substring-without-repeating-characters", difficulty: "Medium" },
  { group: "Two Pointers", title: "3Sum", slug: "3sum", difficulty: "Medium" },
  { group: "Tree", title: "Binary Tree Level Order Traversal", slug: "binary-tree-level-order-traversal", difficulty: "Medium" },
  { group: "Graph", title: "Clone Graph", slug: "clone-graph", difficulty: "Medium" },
  { group: "Stack", title: "Evaluate Reverse Polish Notation", slug: "evaluate-reverse-polish-notation", difficulty: "Medium" },
  { group: "Graph", title: "Course Schedule", slug: "course-schedule", difficulty: "Medium" },
  { group: "Trie", title: "Implement Trie (Prefix Tree)", slug: "implement-trie-prefix-tree", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Coin Change", slug: "coin-change", difficulty: "Medium" },
  { group: "Array", title: "Product of Array Except Self", slug: "product-of-array-except-self", difficulty: "Medium" },
  { group: "Stack", title: "Min Stack", slug: "min-stack", difficulty: "Medium" },
  { group: "Tree", title: "Validate Binary Search Tree", slug: "validate-binary-search-tree", difficulty: "Medium" },
  { group: "Graph", title: "Number of Islands", slug: "number-of-islands", difficulty: "Medium" },
  { group: "Graph", title: "Rotting Oranges", slug: "rotting-oranges", difficulty: "Medium" },
  { group: "Binary Search", title: "Search in Rotated Sorted Array", slug: "search-in-rotated-sorted-array", difficulty: "Medium" },
  { group: "Backtracking", title: "Combination Sum", slug: "combination-sum", difficulty: "Medium" },
  { group: "Backtracking", title: "Permutations", slug: "permutations", difficulty: "Medium" },
  { group: "Interval", title: "Merge Intervals", slug: "merge-intervals", difficulty: "Medium" },
  { group: "Tree", title: "Lowest Common Ancestor of a Binary Tree", slug: "lowest-common-ancestor-of-a-binary-tree", difficulty: "Medium" },
  { group: "Design", title: "Time Based Key-Value Store", slug: "time-based-key-value-store", difficulty: "Medium" },
  { group: "Graph", title: "Accounts Merge", slug: "accounts-merge", difficulty: "Medium" },
  { group: "Two Pointers", title: "Sort Colors", slug: "sort-colors", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Word Break", slug: "word-break", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Partition Equal Subset Sum", slug: "partition-equal-subset-sum", difficulty: "Medium" },
  { group: "String", title: "String to Integer (atoi)", slug: "string-to-integer-atoi", difficulty: "Medium" },
  { group: "Matrix", title: "Spiral Matrix", slug: "spiral-matrix", difficulty: "Medium" },
  { group: "Backtracking", title: "Subsets", slug: "subsets", difficulty: "Medium" },
  { group: "Tree", title: "Binary Tree Right Side View", slug: "binary-tree-right-side-view", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Longest Palindromic Substring", slug: "longest-palindromic-substring", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Unique Paths", slug: "unique-paths", difficulty: "Medium" },
  { group: "Tree", title: "Construct Binary Tree from Preorder and Inorder Traversal", slug: "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty: "Medium" },
  { group: "Two Pointers", title: "Container With Most Water", slug: "container-with-most-water", difficulty: "Medium" },
  { group: "Backtracking", title: "Letter Combinations of a Phone Number", slug: "letter-combinations-of-a-phone-number", difficulty: "Medium" },
  { group: "Backtracking", title: "Word Search", slug: "word-search", difficulty: "Medium" },
  { group: "Sliding Window", title: "Find All Anagrams in a String", slug: "find-all-anagrams-in-a-string", difficulty: "Medium" },
  { group: "Graph", title: "Minimum Height Trees", slug: "minimum-height-trees", difficulty: "Medium" },
  { group: "Heap", title: "Task Scheduler", slug: "task-scheduler", difficulty: "Medium" },
  { group: "Design", title: "LRU Cache", slug: "lru-cache", difficulty: "Medium" },
  { group: "Tree", title: "Kth Smallest Element in a BST", slug: "kth-smallest-element-in-a-bst", difficulty: "Medium" },
  { group: "Sliding Window", title: "Minimum Window Substring", slug: "minimum-window-substring", difficulty: "Hard" },
  { group: "Tree", title: "Serialize and Deserialize Binary Tree", slug: "serialize-and-deserialize-binary-tree", difficulty: "Hard" },
  { group: "Two Pointers", title: "Trapping Rain Water", slug: "trapping-rain-water", difficulty: "Hard" },
  { group: "Heap", title: "Find Median from Data Stream", slug: "find-median-from-data-stream", difficulty: "Hard" },
  { group: "Graph", title: "Word Ladder", slug: "word-ladder", difficulty: "Hard" },
  { group: "Stack", title: "Basic Calculator", slug: "basic-calculator", difficulty: "Hard" },
  { group: "Dynamic Programming", title: "Maximum Profit in Job Scheduling", slug: "maximum-profit-in-job-scheduling", difficulty: "Hard" },
  { group: "Heap", title: "Merge k Sorted Lists", slug: "merge-k-sorted-lists", difficulty: "Hard" },
  { group: "Stack", title: "Largest Rectangle in Histogram", slug: "largest-rectangle-in-histogram", difficulty: "Hard" },
]

const NEETCODE_250: RoadmapProblem[] = [
  { group: "Arrays & Hashing", title: "Concatenation of Array", slug: "concatenation-of-array", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Contains Duplicate", slug: "contains-duplicate", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Valid Anagram", slug: "valid-anagram", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Two Sum", slug: "two-sum", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Longest Common Prefix", slug: "longest-common-prefix", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Group Anagrams", slug: "group-anagrams", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Remove Element", slug: "remove-element", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Majority Element", slug: "majority-element", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Design HashSet", slug: "design-hashset", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Design HashMap", slug: "design-hashmap", difficulty: "Easy" },
  { group: "Arrays & Hashing", title: "Sort an Array", slug: "sort-an-array", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Sort Colors", slug: "sort-colors", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Top K Frequent Elements", slug: "top-k-frequent-elements", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Encode and Decode Strings", slug: "encode-and-decode-strings", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Range Sum Query 2D Immutable", slug: "range-sum-query-2d-immutable", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Product of Array Except Self", slug: "product-of-array-except-self", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Valid Sudoku", slug: "valid-sudoku", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Longest Consecutive Sequence", slug: "longest-consecutive-sequence", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Best Time to Buy And Sell Stock II", slug: "best-time-to-buy-and-sell-stock-ii", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Majority Element II", slug: "majority-element-ii", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "Subarray Sum Equals K", slug: "subarray-sum-equals-k", difficulty: "Medium" },
  { group: "Arrays & Hashing", title: "First Missing Positive", slug: "first-missing-positive", difficulty: "Hard" },
  { group: "Two Pointers", title: "Reverse String", slug: "reverse-string", difficulty: "Easy" },
  { group: "Two Pointers", title: "Valid Palindrome", slug: "valid-palindrome", difficulty: "Easy" },
  { group: "Two Pointers", title: "Valid Palindrome II", slug: "valid-palindrome-ii", difficulty: "Easy" },
  { group: "Two Pointers", title: "Merge Strings Alternately", slug: "merge-strings-alternately", difficulty: "Easy" },
  { group: "Two Pointers", title: "Merge Sorted Array", slug: "merge-sorted-array", difficulty: "Easy" },
  { group: "Two Pointers", title: "Remove Duplicates From Sorted Array", slug: "remove-duplicates-from-sorted-array", difficulty: "Easy" },
  { group: "Two Pointers", title: "Two Sum II Input Array Is Sorted", slug: "two-sum-ii-input-array-is-sorted", difficulty: "Medium" },
  { group: "Two Pointers", title: "3Sum", slug: "3sum", difficulty: "Medium" },
  { group: "Two Pointers", title: "4Sum", slug: "4sum", difficulty: "Medium" },
  { group: "Two Pointers", title: "Rotate Array", slug: "rotate-array", difficulty: "Medium" },
  { group: "Two Pointers", title: "Container With Most Water", slug: "container-with-most-water", difficulty: "Medium" },
  { group: "Two Pointers", title: "Boats to Save People", slug: "boats-to-save-people", difficulty: "Medium" },
  { group: "Two Pointers", title: "Trapping Rain Water", slug: "trapping-rain-water", difficulty: "Hard" },
  { group: "Sliding Window", title: "Contains Duplicate II", slug: "contains-duplicate-ii", difficulty: "Easy" },
  { group: "Sliding Window", title: "Best Time to Buy And Sell Stock", slug: "best-time-to-buy-and-sell-stock", difficulty: "Easy" },
  { group: "Sliding Window", title: "Longest Substring Without Repeating Characters", slug: "longest-substring-without-repeating-characters", difficulty: "Medium" },
  { group: "Sliding Window", title: "Longest Repeating Character Replacement", slug: "longest-repeating-character-replacement", difficulty: "Medium" },
  { group: "Sliding Window", title: "Permutation In String", slug: "permutation-in-string", difficulty: "Medium" },
  { group: "Sliding Window", title: "Minimum Size Subarray Sum", slug: "minimum-size-subarray-sum", difficulty: "Medium" },
  { group: "Sliding Window", title: "Find K Closest Elements", slug: "find-k-closest-elements", difficulty: "Medium" },
  { group: "Sliding Window", title: "Minimum Window Substring", slug: "minimum-window-substring", difficulty: "Hard" },
  { group: "Sliding Window", title: "Sliding Window Maximum", slug: "sliding-window-maximum", difficulty: "Hard" },
  { group: "Stack", title: "Baseball Game", slug: "baseball-game", difficulty: "Easy" },
  { group: "Stack", title: "Valid Parentheses", slug: "valid-parentheses", difficulty: "Easy" },
  { group: "Stack", title: "Implement Stack Using Queues", slug: "implement-stack-using-queues", difficulty: "Easy" },
  { group: "Stack", title: "Implement Queue using Stacks", slug: "implement-queue-using-stacks", difficulty: "Easy" },
  { group: "Stack", title: "Min Stack", slug: "min-stack", difficulty: "Medium" },
  { group: "Stack", title: "Evaluate Reverse Polish Notation", slug: "evaluate-reverse-polish-notation", difficulty: "Medium" },
  { group: "Stack", title: "Generate Parentheses", slug: "generate-parentheses", difficulty: "Medium" },
  { group: "Stack", title: "Asteroid Collision", slug: "asteroid-collision", difficulty: "Medium" },
  { group: "Stack", title: "Daily Temperatures", slug: "daily-temperatures", difficulty: "Medium" },
  { group: "Stack", title: "Online Stock Span", slug: "online-stock-span", difficulty: "Medium" },
  { group: "Stack", title: "Car Fleet", slug: "car-fleet", difficulty: "Medium" },
  { group: "Stack", title: "Simplify Path", slug: "simplify-path", difficulty: "Medium" },
  { group: "Stack", title: "Decode String", slug: "decode-string", difficulty: "Medium" },
  { group: "Stack", title: "Maximum Frequency Stack", slug: "maximum-frequency-stack", difficulty: "Hard" },
  { group: "Stack", title: "Largest Rectangle In Histogram", slug: "largest-rectangle-in-histogram", difficulty: "Hard" },
  { group: "Binary Search", title: "Binary Search", slug: "binary-search", difficulty: "Easy" },
  { group: "Binary Search", title: "Search Insert Position", slug: "search-insert-position", difficulty: "Easy" },
  { group: "Binary Search", title: "Guess Number Higher Or Lower", slug: "guess-number-higher-or-lower", difficulty: "Easy" },
  { group: "Binary Search", title: "Sqrt(x)", slug: "sqrtx", difficulty: "Easy" },
  { group: "Binary Search", title: "Search a 2D Matrix", slug: "search-a-2d-matrix", difficulty: "Medium" },
  { group: "Binary Search", title: "Koko Eating Bananas", slug: "koko-eating-bananas", difficulty: "Medium" },
  { group: "Binary Search", title: "Capacity to Ship Packages Within D Days", slug: "capacity-to-ship-packages-within-d-days", difficulty: "Medium" },
  { group: "Binary Search", title: "Find Minimum In Rotated Sorted Array", slug: "find-minimum-in-rotated-sorted-array", difficulty: "Medium" },
  { group: "Binary Search", title: "Search In Rotated Sorted Array", slug: "search-in-rotated-sorted-array", difficulty: "Medium" },
  { group: "Binary Search", title: "Search In Rotated Sorted Array II", slug: "search-in-rotated-sorted-array-ii", difficulty: "Medium" },
  { group: "Binary Search", title: "Time Based Key Value Store", slug: "time-based-key-value-store", difficulty: "Medium" },
  { group: "Binary Search", title: "Split Array Largest Sum", slug: "split-array-largest-sum", difficulty: "Hard" },
  { group: "Binary Search", title: "Median of Two Sorted Arrays", slug: "median-of-two-sorted-arrays", difficulty: "Hard" },
  { group: "Binary Search", title: "Find in Mountain Array", slug: "find-in-mountain-array", difficulty: "Hard" },
  { group: "Linked List", title: "Reverse Linked List", slug: "reverse-linked-list", difficulty: "Easy" },
  { group: "Linked List", title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists", difficulty: "Easy" },
  { group: "Linked List", title: "Linked List Cycle", slug: "linked-list-cycle", difficulty: "Easy" },
  { group: "Linked List", title: "Reorder List", slug: "reorder-list", difficulty: "Medium" },
  { group: "Linked List", title: "Remove Nth Node From End of List", slug: "remove-nth-node-from-end-of-list", difficulty: "Medium" },
  { group: "Linked List", title: "Copy List With Random Pointer", slug: "copy-list-with-random-pointer", difficulty: "Medium" },
  { group: "Linked List", title: "Add Two Numbers", slug: "add-two-numbers", difficulty: "Medium" },
  { group: "Linked List", title: "Find The Duplicate Number", slug: "find-the-duplicate-number", difficulty: "Medium" },
  { group: "Linked List", title: "Reverse Linked List II", slug: "reverse-linked-list-ii", difficulty: "Medium" },
  { group: "Linked List", title: "Design Circular Queue", slug: "design-circular-queue", difficulty: "Medium" },
  { group: "Linked List", title: "LRU Cache", slug: "lru-cache", difficulty: "Medium" },
  { group: "Linked List", title: "LFU Cache", slug: "lfu-cache", difficulty: "Hard" },
  { group: "Linked List", title: "Merge K Sorted Lists", slug: "merge-k-sorted-lists", difficulty: "Hard" },
  { group: "Linked List", title: "Reverse Nodes In K Group", slug: "reverse-nodes-in-k-group", difficulty: "Hard" },
  { group: "Trees", title: "Binary Tree Inorder Traversal", slug: "binary-tree-inorder-traversal", difficulty: "Easy" },
  { group: "Trees", title: "Binary Tree Preorder Traversal", slug: "binary-tree-preorder-traversal", difficulty: "Easy" },
  { group: "Trees", title: "Binary Tree Postorder Traversal", slug: "binary-tree-postorder-traversal", difficulty: "Easy" },
  { group: "Trees", title: "Invert Binary Tree", slug: "invert-binary-tree", difficulty: "Easy" },
  { group: "Trees", title: "Maximum Depth of Binary Tree", slug: "maximum-depth-of-binary-tree", difficulty: "Easy" },
  { group: "Trees", title: "Diameter of Binary Tree", slug: "diameter-of-binary-tree", difficulty: "Easy" },
  { group: "Trees", title: "Balanced Binary Tree", slug: "balanced-binary-tree", difficulty: "Easy" },
  { group: "Trees", title: "Same Tree", slug: "same-tree", difficulty: "Easy" },
  { group: "Trees", title: "Subtree of Another Tree", slug: "subtree-of-another-tree", difficulty: "Easy" },
  { group: "Trees", title: "Lowest Common Ancestor of a Binary Search Tree", slug: "lowest-common-ancestor-of-a-binary-search-tree", difficulty: "Medium" },
  { group: "Trees", title: "Insert into a Binary Search Tree", slug: "insert-into-a-binary-search-tree", difficulty: "Medium" },
  { group: "Trees", title: "Delete Node in a BST", slug: "delete-node-in-a-bst", difficulty: "Medium" },
  { group: "Trees", title: "Binary Tree Level Order Traversal", slug: "binary-tree-level-order-traversal", difficulty: "Medium" },
  { group: "Trees", title: "Binary Tree Right Side View", slug: "binary-tree-right-side-view", difficulty: "Medium" },
  { group: "Trees", title: "Construct Quad Tree", slug: "construct-quad-tree", difficulty: "Medium" },
  { group: "Trees", title: "Count Good Nodes In Binary Tree", slug: "count-good-nodes-in-binary-tree", difficulty: "Medium" },
  { group: "Trees", title: "Validate Binary Search Tree", slug: "validate-binary-search-tree", difficulty: "Medium" },
  { group: "Trees", title: "Kth Smallest Element In a Bst", slug: "kth-smallest-element-in-a-bst", difficulty: "Medium" },
  { group: "Trees", title: "Construct Binary Tree From Preorder And Inorder Traversal", slug: "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty: "Medium" },
  { group: "Trees", title: "House Robber III", slug: "house-robber-iii", difficulty: "Medium" },
  { group: "Trees", title: "Delete Leaves With a Given Value", slug: "delete-leaves-with-a-given-value", difficulty: "Medium" },
  { group: "Trees", title: "Binary Tree Maximum Path Sum", slug: "binary-tree-maximum-path-sum", difficulty: "Hard" },
  { group: "Trees", title: "Serialize And Deserialize Binary Tree", slug: "serialize-and-deserialize-binary-tree", difficulty: "Hard" },
  { group: "Heap / Priority Queue", title: "Kth Largest Element In a Stream", slug: "kth-largest-element-in-a-stream", difficulty: "Easy" },
  { group: "Heap / Priority Queue", title: "Last Stone Weight", slug: "last-stone-weight", difficulty: "Easy" },
  { group: "Heap / Priority Queue", title: "K Closest Points to Origin", slug: "k-closest-points-to-origin", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Kth Largest Element In An Array", slug: "kth-largest-element-in-an-array", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Task Scheduler", slug: "task-scheduler", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Design Twitter", slug: "design-twitter", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Single Threaded CPU", slug: "single-threaded-cpu", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Reorganize String", slug: "reorganize-string", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Longest Happy String", slug: "longest-happy-string", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Car Pooling", slug: "car-pooling", difficulty: "Medium" },
  { group: "Heap / Priority Queue", title: "Find Median From Data Stream", slug: "find-median-from-data-stream", difficulty: "Hard" },
  { group: "Heap / Priority Queue", title: "IPO", slug: "ipo", difficulty: "Hard" },
  { group: "Backtracking", title: "Sum of All Subset XOR Totals", slug: "sum-of-all-subset-xor-totals", difficulty: "Easy" },
  { group: "Backtracking", title: "Subsets", slug: "subsets", difficulty: "Medium" },
  { group: "Backtracking", title: "Combination Sum", slug: "combination-sum", difficulty: "Medium" },
  { group: "Backtracking", title: "Combination Sum II", slug: "combination-sum-ii", difficulty: "Medium" },
  { group: "Backtracking", title: "Combinations", slug: "combinations", difficulty: "Medium" },
  { group: "Backtracking", title: "Permutations", slug: "permutations", difficulty: "Medium" },
  { group: "Backtracking", title: "Subsets II", slug: "subsets-ii", difficulty: "Medium" },
  { group: "Backtracking", title: "Permutations II", slug: "permutations-ii", difficulty: "Medium" },
  { group: "Backtracking", title: "Word Search", slug: "word-search", difficulty: "Medium" },
  { group: "Backtracking", title: "Palindrome Partitioning", slug: "palindrome-partitioning", difficulty: "Medium" },
  { group: "Backtracking", title: "Letter Combinations of a Phone Number", slug: "letter-combinations-of-a-phone-number", difficulty: "Medium" },
  { group: "Backtracking", title: "Matchsticks to Square", slug: "matchsticks-to-square", difficulty: "Medium" },
  { group: "Backtracking", title: "Partition to K Equal Sum Subsets", slug: "partition-to-k-equal-sum-subsets", difficulty: "Medium" },
  { group: "Backtracking", title: "N Queens", slug: "n-queens", difficulty: "Hard" },
  { group: "Backtracking", title: "N Queens II", slug: "n-queens-ii", difficulty: "Hard" },
  { group: "Backtracking", title: "Word Break II", slug: "word-break-ii", difficulty: "Hard" },
  { group: "Tries", title: "Implement Trie Prefix Tree", slug: "implement-trie-prefix-tree", difficulty: "Medium" },
  { group: "Tries", title: "Design Add And Search Words Data Structure", slug: "design-add-and-search-words-data-structure", difficulty: "Medium" },
  { group: "Tries", title: "Extra Characters in a String", slug: "extra-characters-in-a-string", difficulty: "Medium" },
  { group: "Tries", title: "Word Search II", slug: "word-search-ii", difficulty: "Hard" },
  { group: "Graphs", title: "Island Perimeter", slug: "island-perimeter", difficulty: "Easy" },
  { group: "Graphs", title: "Verifying An Alien Dictionary", slug: "verifying-an-alien-dictionary", difficulty: "Easy" },
  { group: "Graphs", title: "Find the Town Judge", slug: "find-the-town-judge", difficulty: "Easy" },
  { group: "Graphs", title: "Number of Islands", slug: "number-of-islands", difficulty: "Medium" },
  { group: "Graphs", title: "Max Area of Island", slug: "max-area-of-island", difficulty: "Medium" },
  { group: "Graphs", title: "Clone Graph", slug: "clone-graph", difficulty: "Medium" },
  { group: "Graphs", title: "Walls And Gates", slug: "walls-and-gates", difficulty: "Medium" },
  { group: "Graphs", title: "Rotting Oranges", slug: "rotting-oranges", difficulty: "Medium" },
  { group: "Graphs", title: "Pacific Atlantic Water Flow", slug: "pacific-atlantic-water-flow", difficulty: "Medium" },
  { group: "Graphs", title: "Surrounded Regions", slug: "surrounded-regions", difficulty: "Medium" },
  { group: "Graphs", title: "Open The Lock", slug: "open-the-lock", difficulty: "Medium" },
  { group: "Graphs", title: "Course Schedule", slug: "course-schedule", difficulty: "Medium" },
  { group: "Graphs", title: "Course Schedule II", slug: "course-schedule-ii", difficulty: "Medium" },
  { group: "Graphs", title: "Graph Valid Tree", slug: "graph-valid-tree", difficulty: "Medium" },
  { group: "Graphs", title: "Course Schedule IV", slug: "course-schedule-iv", difficulty: "Medium" },
  { group: "Graphs", title: "Number of Connected Components In An Undirected Graph", slug: "number-of-connected-components-in-an-undirected-graph", difficulty: "Medium" },
  { group: "Graphs", title: "Redundant Connection", slug: "redundant-connection", difficulty: "Medium" },
  { group: "Graphs", title: "Accounts Merge", slug: "accounts-merge", difficulty: "Medium" },
  { group: "Graphs", title: "Evaluate Division", slug: "evaluate-division", difficulty: "Medium" },
  { group: "Graphs", title: "Minimum Height Trees", slug: "minimum-height-trees", difficulty: "Medium" },
  { group: "Graphs", title: "Word Ladder", slug: "word-ladder", difficulty: "Hard" },
  { group: "Advanced Graphs", title: "Path with Minimum Effort", slug: "path-with-minimum-effort", difficulty: "Medium" },
  { group: "Advanced Graphs", title: "Network Delay Time", slug: "network-delay-time", difficulty: "Medium" },
  { group: "Advanced Graphs", title: "Reconstruct Itinerary", slug: "reconstruct-itinerary", difficulty: "Hard" },
  { group: "Advanced Graphs", title: "Min Cost to Connect All Points", slug: "min-cost-to-connect-all-points", difficulty: "Medium" },
  { group: "Advanced Graphs", title: "Swim In Rising Water", slug: "swim-in-rising-water", difficulty: "Hard" },
  { group: "Advanced Graphs", title: "Alien Dictionary", slug: "alien-dictionary", difficulty: "Hard" },
  { group: "Advanced Graphs", title: "Cheapest Flights Within K Stops", slug: "cheapest-flights-within-k-stops", difficulty: "Medium" },
  { group: "Advanced Graphs", title: "Find Critical and Pseudo Critical Edges in Minimum Spanning Tree", slug: "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree", difficulty: "Hard" },
  { group: "Advanced Graphs", title: "Build a Matrix With Conditions", slug: "build-a-matrix-with-conditions", difficulty: "Hard" },
  { group: "Advanced Graphs", title: "Greatest Common Divisor Traversal", slug: "greatest-common-divisor-traversal", difficulty: "Hard" },
  { group: "1-D DP", title: "Climbing Stairs", slug: "climbing-stairs", difficulty: "Easy" },
  { group: "1-D DP", title: "Min Cost Climbing Stairs", slug: "min-cost-climbing-stairs", difficulty: "Easy" },
  { group: "1-D DP", title: "N-th Tribonacci Number", slug: "n-th-tribonacci-number", difficulty: "Easy" },
  { group: "1-D DP", title: "House Robber", slug: "house-robber", difficulty: "Medium" },
  { group: "1-D DP", title: "House Robber II", slug: "house-robber-ii", difficulty: "Medium" },
  { group: "1-D DP", title: "Longest Palindromic Substring", slug: "longest-palindromic-substring", difficulty: "Medium" },
  { group: "1-D DP", title: "Palindromic Substrings", slug: "palindromic-substrings", difficulty: "Medium" },
  { group: "1-D DP", title: "Decode Ways", slug: "decode-ways", difficulty: "Medium" },
  { group: "1-D DP", title: "Coin Change", slug: "coin-change", difficulty: "Medium" },
  { group: "1-D DP", title: "Maximum Product Subarray", slug: "maximum-product-subarray", difficulty: "Medium" },
  { group: "1-D DP", title: "Word Break", slug: "word-break", difficulty: "Medium" },
  { group: "1-D DP", title: "Longest Increasing Subsequence", slug: "longest-increasing-subsequence", difficulty: "Medium" },
  { group: "1-D DP", title: "Partition Equal Subset Sum", slug: "partition-equal-subset-sum", difficulty: "Medium" },
  { group: "1-D DP", title: "Combination Sum IV", slug: "combination-sum-iv", difficulty: "Medium" },
  { group: "1-D DP", title: "Perfect Squares", slug: "perfect-squares", difficulty: "Medium" },
  { group: "1-D DP", title: "Integer Break", slug: "integer-break", difficulty: "Medium" },
  { group: "1-D DP", title: "Stone Game III", slug: "stone-game-iii", difficulty: "Hard" },
  { group: "2-D DP", title: "Unique Paths", slug: "unique-paths", difficulty: "Medium" },
  { group: "2-D DP", title: "Unique Paths II", slug: "unique-paths-ii", difficulty: "Medium" },
  { group: "2-D DP", title: "Minimum Path Sum", slug: "minimum-path-sum", difficulty: "Medium" },
  { group: "2-D DP", title: "Longest Common Subsequence", slug: "longest-common-subsequence", difficulty: "Medium" },
  { group: "2-D DP", title: "Last Stone Weight II", slug: "last-stone-weight-ii", difficulty: "Medium" },
  { group: "2-D DP", title: "Best Time to Buy And Sell Stock With Cooldown", slug: "best-time-to-buy-and-sell-stock-with-cooldown", difficulty: "Medium" },
  { group: "2-D DP", title: "Coin Change II", slug: "coin-change-ii", difficulty: "Medium" },
  { group: "2-D DP", title: "Target Sum", slug: "target-sum", difficulty: "Medium" },
  { group: "2-D DP", title: "Interleaving String", slug: "interleaving-string", difficulty: "Medium" },
  { group: "2-D DP", title: "Stone Game", slug: "stone-game", difficulty: "Medium" },
  { group: "2-D DP", title: "Stone Game II", slug: "stone-game-ii", difficulty: "Medium" },
  { group: "2-D DP", title: "Longest Increasing Path In a Matrix", slug: "longest-increasing-path-in-a-matrix", difficulty: "Hard" },
  { group: "2-D DP", title: "Distinct Subsequences", slug: "distinct-subsequences", difficulty: "Hard" },
  { group: "2-D DP", title: "Edit Distance", slug: "edit-distance", difficulty: "Medium" },
  { group: "2-D DP", title: "Burst Balloons", slug: "burst-balloons", difficulty: "Hard" },
  { group: "2-D DP", title: "Regular Expression Matching", slug: "regular-expression-matching", difficulty: "Hard" },
  { group: "Greedy", title: "Lemonade Change", slug: "lemonade-change", difficulty: "Easy" },
  { group: "Greedy", title: "Maximum Subarray", slug: "maximum-subarray", difficulty: "Medium" },
  { group: "Greedy", title: "Maximum Sum Circular Subarray", slug: "maximum-sum-circular-subarray", difficulty: "Medium" },
  { group: "Greedy", title: "Longest Turbulent Subarray", slug: "longest-turbulent-subarray", difficulty: "Medium" },
  { group: "Greedy", title: "Jump Game", slug: "jump-game", difficulty: "Medium" },
  { group: "Greedy", title: "Jump Game II", slug: "jump-game-ii", difficulty: "Medium" },
  { group: "Greedy", title: "Jump Game VII", slug: "jump-game-vii", difficulty: "Medium" },
  { group: "Greedy", title: "Gas Station", slug: "gas-station", difficulty: "Medium" },
  { group: "Greedy", title: "Hand of Straights", slug: "hand-of-straights", difficulty: "Medium" },
  { group: "Greedy", title: "Dota2 Senate", slug: "dota2-senate", difficulty: "Medium" },
  { group: "Greedy", title: "Merge Triplets to Form Target Triplet", slug: "merge-triplets-to-form-target-triplet", difficulty: "Medium" },
  { group: "Greedy", title: "Partition Labels", slug: "partition-labels", difficulty: "Medium" },
  { group: "Greedy", title: "Valid Parenthesis String", slug: "valid-parenthesis-string", difficulty: "Medium" },
  { group: "Greedy", title: "Candy", slug: "candy", difficulty: "Hard" },
  { group: "Intervals", title: "Insert Interval", slug: "insert-interval", difficulty: "Medium" },
  { group: "Intervals", title: "Merge Intervals", slug: "merge-intervals", difficulty: "Medium" },
  { group: "Intervals", title: "Non Overlapping Intervals", slug: "non-overlapping-intervals", difficulty: "Medium" },
  { group: "Intervals", title: "Meeting Rooms", slug: "meeting-rooms", difficulty: "Easy" },
  { group: "Intervals", title: "Meeting Rooms II", slug: "meeting-rooms-ii", difficulty: "Medium" },
  { group: "Intervals", title: "Meeting Rooms III", slug: "meeting-rooms-iii", difficulty: "Hard" },
  { group: "Intervals", title: "Minimum Interval to Include Each Query", slug: "minimum-interval-to-include-each-query", difficulty: "Hard" },
  { group: "Math & Geometry", title: "Excel Sheet Column Title", slug: "excel-sheet-column-title", difficulty: "Easy" },
  { group: "Math & Geometry", title: "Greatest Common Divisor of Strings", slug: "greatest-common-divisor-of-strings", difficulty: "Easy" },
  { group: "Math & Geometry", title: "Insert Greatest Common Divisors in Linked List", slug: "insert-greatest-common-divisors-in-linked-list", difficulty: "Medium" },
  { group: "Math & Geometry", title: "Transpose Matrix", slug: "transpose-matrix", difficulty: "Easy" },
  { group: "Math & Geometry", title: "Rotate Image", slug: "rotate-image", difficulty: "Medium" },
  { group: "Math & Geometry", title: "Spiral Matrix", slug: "spiral-matrix", difficulty: "Medium" },
  { group: "Math & Geometry", title: "Set Matrix Zeroes", slug: "set-matrix-zeroes", difficulty: "Medium" },
  { group: "Math & Geometry", title: "Happy Number", slug: "happy-number", difficulty: "Easy" },
  { group: "Math & Geometry", title: "Plus One", slug: "plus-one", difficulty: "Easy" },
  { group: "Math & Geometry", title: "Roman to Integer", slug: "roman-to-integer", difficulty: "Easy" },
  { group: "Math & Geometry", title: "Pow(x, n)", slug: "powx-n", difficulty: "Medium" },
  { group: "Math & Geometry", title: "Multiply Strings", slug: "multiply-strings", difficulty: "Medium" },
  { group: "Math & Geometry", title: "Detect Squares", slug: "detect-squares", difficulty: "Medium" },
  { group: "Bit Manipulation", title: "Single Number", slug: "single-number", difficulty: "Easy" },
  { group: "Bit Manipulation", title: "Number of 1 Bits", slug: "number-of-1-bits", difficulty: "Easy" },
  { group: "Bit Manipulation", title: "Counting Bits", slug: "counting-bits", difficulty: "Easy" },
  { group: "Bit Manipulation", title: "Add Binary", slug: "add-binary", difficulty: "Easy" },
  { group: "Bit Manipulation", title: "Reverse Bits", slug: "reverse-bits", difficulty: "Easy" },
  { group: "Bit Manipulation", title: "Missing Number", slug: "missing-number", difficulty: "Easy" },
  { group: "Bit Manipulation", title: "Sum of Two Integers", slug: "sum-of-two-integers", difficulty: "Medium" },
  { group: "Bit Manipulation", title: "Reverse Integer", slug: "reverse-integer", difficulty: "Medium" },
  { group: "Bit Manipulation", title: "Bitwise AND of Numbers Range", slug: "bitwise-and-of-numbers-range", difficulty: "Medium" },
  { group: "Bit Manipulation", title: "Minimum Array End", slug: "minimum-array-end", difficulty: "Medium" },
]

const STRIVER_SDE: RoadmapProblem[] = [
  { group: "Arrays", title: "Set Matrix Zeroes", slug: "set-matrix-zeroes", difficulty: "Medium" },
  { group: "Arrays", title: "Pascal's Triangle", slug: "pascals-triangle", difficulty: "Easy" },
  { group: "Arrays", title: "Next Permutation", slug: "next-permutation", difficulty: "Medium" },
  { group: "Arrays", title: "Kadane's Algorithm (Maximum Subarray)", slug: "maximum-subarray", difficulty: "Medium" },
  { group: "Arrays", title: "Sort Colors (0s, 1s and 2s)", slug: "sort-colors", difficulty: "Medium" },
  { group: "Arrays", title: "Best Time to Buy and Sell Stock", slug: "best-time-to-buy-and-sell-stock", difficulty: "Easy" },
  { group: "Arrays", title: "Rotate Image", slug: "rotate-image", difficulty: "Medium" },
  { group: "Arrays", title: "Merge Intervals", slug: "merge-intervals", difficulty: "Medium" },
  { group: "Arrays", title: "Merge Two Sorted Arrays Without Extra Space", slug: "merge-sorted-array", difficulty: "Medium" },
  { group: "Arrays", title: "Find the Duplicate Number", slug: "find-the-duplicate-number", difficulty: "Medium" },
  { group: "Arrays", title: "Repeat and Missing Number", slug: "repeat-and-missing-number", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/find-missing-and-repeating2512/1" },
  { group: "Arrays", title: "Count Inversions", slug: "count-inversions", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1" },
  { group: "Arrays", title: "Search in a 2D Matrix", slug: "search-a-2d-matrix", difficulty: "Medium" },
  { group: "Arrays", title: "Pow(x, n)", slug: "powx-n", difficulty: "Medium" },
  { group: "Arrays", title: "Majority Element (> N/2 times)", slug: "majority-element", difficulty: "Easy" },
  { group: "Arrays", title: "Majority Element (> N/3 times)", slug: "majority-element-ii", difficulty: "Medium" },
  { group: "Arrays", title: "Unique Paths", slug: "unique-paths", difficulty: "Medium" },
  { group: "Arrays", title: "Reverse Pairs", slug: "reverse-pairs", difficulty: "Hard" },
  { group: "Arrays", title: "Two Sum", slug: "two-sum", difficulty: "Easy" },
  { group: "Arrays", title: "4 Sum", slug: "4sum", difficulty: "Medium" },
  { group: "Arrays", title: "Longest Consecutive Sequence", slug: "longest-consecutive-sequence", difficulty: "Medium" },
  { group: "Arrays", title: "Largest Subarray with 0 Sum", slug: "largest-subarray-with-0-sum", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1" },
  { group: "Arrays", title: "Count Subarrays with Given XOR K", slug: "subarray-with-given-xor", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/subarray-with-given-xor/1" },
  { group: "Arrays", title: "Longest Substring Without Repeating Characters", slug: "longest-substring-without-repeating-characters", difficulty: "Medium" },
  { group: "Linked List", title: "Reverse a Linked List", slug: "reverse-linked-list", difficulty: "Easy" },
  { group: "Linked List", title: "Middle of the Linked List", slug: "middle-of-the-linked-list", difficulty: "Easy" },
  { group: "Linked List", title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists", difficulty: "Easy" },
  { group: "Linked List", title: "Remove Nth Node From End of List", slug: "remove-nth-node-from-end-of-list", difficulty: "Medium" },
  { group: "Linked List", title: "Add Two Numbers", slug: "add-two-numbers", difficulty: "Medium" },
  { group: "Linked List", title: "Delete Node in a Linked List", slug: "delete-node-in-a-linked-list", difficulty: "Medium" },
  { group: "Linked List", title: "Intersection of Two Linked Lists", slug: "intersection-of-two-linked-lists", difficulty: "Easy" },
  { group: "Linked List", title: "Linked List Cycle", slug: "linked-list-cycle", difficulty: "Easy" },
  { group: "Linked List", title: "Reverse Nodes in k-Group", slug: "reverse-nodes-in-k-group", difficulty: "Hard" },
  { group: "Linked List", title: "Palindrome Linked List", slug: "palindrome-linked-list", difficulty: "Easy" },
  { group: "Linked List", title: "Linked List Cycle II (Starting Point of Loop)", slug: "linked-list-cycle-ii", difficulty: "Medium" },
  { group: "Linked List", title: "Flattening a Linked List", slug: "flattening-a-linked-list", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1" },
  { group: "Linked List", title: "Rotate List", slug: "rotate-list", difficulty: "Medium" },
  { group: "Linked List", title: "Copy List with Random Pointer", slug: "copy-list-with-random-pointer", difficulty: "Medium" },
  { group: "Arrays", title: "3 Sum", slug: "3sum", difficulty: "Medium" },
  { group: "Arrays", title: "Trapping Rain Water", slug: "trapping-rain-water", difficulty: "Hard" },
  { group: "Arrays", title: "Remove Duplicates from Sorted Array", slug: "remove-duplicates-from-sorted-array", difficulty: "Easy" },
  { group: "Arrays", title: "Max Consecutive Ones", slug: "max-consecutive-ones", difficulty: "Easy" },
  { group: "Greedy", title: "N Meetings in One Room", slug: "n-meetings-in-one-room", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1" },
  { group: "Greedy", title: "Minimum Number of Platforms", slug: "minimum-platforms", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1" },
  { group: "Greedy", title: "Job Sequencing Problem", slug: "job-sequencing-problem", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1" },
  { group: "Greedy", title: "Fractional Knapsack", slug: "fractional-knapsack", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1" },
  { group: "Greedy", title: "Minimum Number of Coins", slug: "number-of-coins", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/number-of-coins1824/1" },
  { group: "Greedy", title: "Assign Cookies", slug: "assign-cookies", difficulty: "Easy" },
  { group: "Recursion", title: "Subset Sums", slug: "subset-sums", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/subset-sums2234/1" },
  { group: "Recursion", title: "Subsets II", slug: "subsets-ii", difficulty: "Medium" },
  { group: "Recursion", title: "Combination Sum", slug: "combination-sum", difficulty: "Medium" },
  { group: "Recursion", title: "Combination Sum II", slug: "combination-sum-ii", difficulty: "Medium" },
  { group: "Recursion", title: "Palindrome Partitioning", slug: "palindrome-partitioning", difficulty: "Medium" },
  { group: "Recursion", title: "Kth Permutation Sequence", slug: "permutation-sequence", difficulty: "Hard" },
  { group: "Backtracking", title: "Print All Permutations", slug: "permutations", difficulty: "Medium" },
  { group: "Backtracking", title: "N-Queens", slug: "n-queens", difficulty: "Hard" },
  { group: "Backtracking", title: "Sudoku Solver", slug: "sudoku-solver", difficulty: "Hard" },
  { group: "Backtracking", title: "M-Coloring Problem", slug: "m-coloring-problem", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1" },
  { group: "Backtracking", title: "Rat in a Maze", slug: "rat-in-a-maze", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1" },
  { group: "Backtracking", title: "Word Break II (Print All Ways)", slug: "word-break-ii", difficulty: "Hard" },
  { group: "Binary Search", title: "Nth Root of an Integer", slug: "nth-root-of-a-number", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/find-nth-root-of-m5843/1" },
  { group: "Binary Search", title: "Matrix Median", slug: "matrix-median", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1" },
  { group: "Binary Search", title: "Single Element in a Sorted Array", slug: "single-element-in-a-sorted-array", difficulty: "Medium" },
  { group: "Binary Search", title: "Search in Rotated Sorted Array", slug: "search-in-rotated-sorted-array", difficulty: "Medium" },
  { group: "Binary Search", title: "Median of Two Sorted Arrays", slug: "median-of-two-sorted-arrays", difficulty: "Hard" },
  { group: "Binary Search", title: "Kth Element of Two Sorted Arrays", slug: "kth-element-of-two-sorted-arrays", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1" },
  { group: "Binary Search", title: "Allocate Minimum Number of Pages", slug: "allocate-minimum-pages", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1" },
  { group: "Binary Search", title: "Aggressive Cows", slug: "aggressive-cows", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/aggressive-cows/1" },
  { group: "Heap", title: "Kth Largest Element in an Array", slug: "kth-largest-element-in-an-array", difficulty: "Medium" },
  { group: "Heap", title: "Maximum Sum Combination", slug: "maximum-sum-combination", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/maximum-sum-combination/1" },
  { group: "Heap", title: "Find Median from Data Stream", slug: "find-median-from-data-stream", difficulty: "Hard" },
  { group: "Heap", title: "Merge K Sorted Arrays", slug: "merge-k-sorted-arrays", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/merge-k-sorted-arrays/1" },
  { group: "Heap", title: "Top K Frequent Elements", slug: "top-k-frequent-elements", difficulty: "Medium" },
  { group: "Stack & Queue", title: "Implement Stack using Arrays", slug: "implement-stack-using-array", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/implement-stack-using-array/1" },
  { group: "Stack & Queue", title: "Implement Queue using Arrays", slug: "implement-queue-using-array", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/implement-queue-using-array/1" },
  { group: "Stack & Queue", title: "Implement Stack using Queues", slug: "implement-stack-using-queues", difficulty: "Easy" },
  { group: "Stack & Queue", title: "Implement Queue using Stacks", slug: "implement-queue-using-stacks", difficulty: "Easy" },
  { group: "Stack & Queue", title: "Valid Parentheses", slug: "valid-parentheses", difficulty: "Easy" },
  { group: "Stack & Queue", title: "Next Greater Element", slug: "next-greater-element-i", difficulty: "Easy" },
  { group: "Stack & Queue", title: "Sort a Stack", slug: "sort-a-stack", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/sort-a-stack/1" },
  { group: "Stack & Queue", title: "LRU Cache", slug: "lru-cache", difficulty: "Medium" },
  { group: "Stack & Queue", title: "LFU Cache", slug: "lfu-cache", difficulty: "Hard" },
  { group: "Stack & Queue", title: "Largest Rectangle in Histogram", slug: "largest-rectangle-in-histogram", difficulty: "Hard" },
  { group: "Stack & Queue", title: "Sliding Window Maximum", slug: "sliding-window-maximum", difficulty: "Hard" },
  { group: "Stack & Queue", title: "Min Stack", slug: "min-stack", difficulty: "Medium" },
  { group: "Stack & Queue", title: "Rotting Oranges", slug: "rotting-oranges", difficulty: "Medium" },
  { group: "Stack & Queue", title: "Stock Span Problem", slug: "online-stock-span", difficulty: "Medium" },
  { group: "Stack & Queue", title: "The Celebrity Problem", slug: "the-celebrity-problem", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/the-celebrity-problem/1" },
  { group: "String", title: "Reverse Words in a String", slug: "reverse-words-in-a-string", difficulty: "Medium" },
  { group: "String", title: "Longest Palindromic Substring", slug: "longest-palindromic-substring", difficulty: "Medium" },
  { group: "String", title: "Roman to Integer", slug: "roman-to-integer", difficulty: "Easy" },
  { group: "String", title: "String to Integer (atoi)", slug: "string-to-integer-atoi", difficulty: "Medium" },
  { group: "String", title: "Longest Common Prefix", slug: "longest-common-prefix", difficulty: "Easy" },
  { group: "String", title: "Minimum Characters to Add Front to Make Palindrome", slug: "min-chars-front-palindrome", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/minimum-characters-to-be-added-at-front-to-make-string-palindrome/1" },
  { group: "String", title: "Valid Anagram", slug: "valid-anagram", difficulty: "Easy" },
  { group: "String", title: "Count and Say", slug: "count-and-say", difficulty: "Medium" },
  { group: "String", title: "Compare Version Numbers", slug: "compare-version-numbers", difficulty: "Medium" },
  { group: "Binary Tree", title: "Inorder Traversal", slug: "binary-tree-inorder-traversal", difficulty: "Easy" },
  { group: "Binary Tree", title: "Preorder Traversal", slug: "binary-tree-preorder-traversal", difficulty: "Easy" },
  { group: "Binary Tree", title: "Postorder Traversal", slug: "binary-tree-postorder-traversal", difficulty: "Easy" },
  { group: "Binary Tree", title: "Left View of Binary Tree", slug: "left-view-of-binary-tree", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/left-view-of-binary-tree/1" },
  { group: "Binary Tree", title: "Bottom View of Binary Tree", slug: "bottom-view-of-binary-tree", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1" },
  { group: "Binary Tree", title: "Top View of Binary Tree", slug: "top-view-of-binary-tree", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/top-view-of-binary-tree/1" },
  { group: "Binary Tree", title: "Vertical Order Traversal of a Binary Tree", slug: "vertical-order-traversal-of-a-binary-tree", difficulty: "Hard" },
  { group: "Binary Tree", title: "Maximum Width of Binary Tree", slug: "maximum-width-of-binary-tree", difficulty: "Medium" },
  { group: "Binary Tree", title: "Level Order Traversal", slug: "binary-tree-level-order-traversal", difficulty: "Medium" },
  { group: "Binary Tree", title: "Height of a Binary Tree", slug: "maximum-depth-of-binary-tree", difficulty: "Easy" },
  { group: "Binary Tree", title: "Diameter of Binary Tree", slug: "diameter-of-binary-tree", difficulty: "Easy" },
  { group: "Binary Tree", title: "Check if Binary Tree is Height Balanced", slug: "balanced-binary-tree", difficulty: "Easy" },
  { group: "Binary Tree", title: "LCA in Binary Tree", slug: "lowest-common-ancestor-of-a-binary-tree", difficulty: "Medium" },
  { group: "Binary Tree", title: "Check if Two Trees are Identical", slug: "same-tree", difficulty: "Easy" },
  { group: "Binary Tree", title: "Zig Zag Traversal of Binary Tree", slug: "binary-tree-zigzag-level-order-traversal", difficulty: "Medium" },
  { group: "Binary Tree", title: "Boundary Traversal of Binary Tree", slug: "boundary-traversal-of-binary-tree", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1" },
  { group: "Binary Tree", title: "Maximum Path Sum", slug: "binary-tree-maximum-path-sum", difficulty: "Hard" },
  { group: "Binary Tree", title: "Construct Binary Tree from Preorder and Inorder", slug: "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty: "Medium" },
  { group: "Binary Tree", title: "Construct Binary Tree from Inorder and Postorder", slug: "construct-binary-tree-from-inorder-and-postorder-traversal", difficulty: "Medium" },
  { group: "Binary Tree", title: "Symmetric Binary Tree", slug: "symmetric-tree", difficulty: "Easy" },
  { group: "Binary Tree", title: "Flatten Binary Tree to Linked List", slug: "flatten-binary-tree-to-linked-list", difficulty: "Medium" },
  { group: "Binary Search Tree", title: "Populate Next Right Pointers of Tree", slug: "populating-next-right-pointers-in-each-node", difficulty: "Medium" },
  { group: "Binary Search Tree", title: "Search Given Key in BST", slug: "search-in-a-binary-search-tree", difficulty: "Easy" },
  { group: "Binary Search Tree", title: "Construct BST from Preorder Traversal", slug: "construct-binary-search-tree-from-preorder-traversal", difficulty: "Medium" },
  { group: "Binary Search Tree", title: "Validate Binary Search Tree", slug: "validate-binary-search-tree", difficulty: "Medium" },
  { group: "Binary Search Tree", title: "LCA of Two Nodes in BST", slug: "lowest-common-ancestor-of-a-binary-search-tree", difficulty: "Medium" },
  { group: "Binary Search Tree", title: "Inorder Predecessor and Successor in BST", slug: "predecessor-successor-bst", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/predecessor-and-successor/1" },
  { group: "Binary Search Tree", title: "Floor in a BST", slug: "floor-in-bst", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/floor-in-bst/1" },
  { group: "Binary Search Tree", title: "Ceil in a BST", slug: "ceil-in-bst", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/implementing-ceil-in-bst/1" },
  { group: "Binary Search Tree", title: "Kth Smallest Element in a BST", slug: "kth-smallest-element-in-a-bst", difficulty: "Medium" },
  { group: "Binary Search Tree", title: "Two Sum IV - Input is a BST", slug: "two-sum-iv-input-is-a-bst", difficulty: "Easy" },
  { group: "Binary Search Tree", title: "BST Iterator", slug: "binary-search-tree-iterator", difficulty: "Medium" },
  { group: "Binary Search Tree", title: "Size of the Largest BST in a Binary Tree", slug: "largest-bst", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/largest-bst/1" },
  { group: "Binary Tree", title: "Serialize and Deserialize Binary Tree", slug: "serialize-and-deserialize-binary-tree", difficulty: "Hard" },
  { group: "Binary Tree", title: "Find Median in a Stream", slug: "find-median-in-a-stream", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/find-median-in-a-stream-1587115620/1" },
  { group: "Graph", title: "Flood Fill", slug: "flood-fill", difficulty: "Easy" },
  { group: "Graph", title: "Clone Graph", slug: "clone-graph", difficulty: "Medium" },
  { group: "Graph", title: "DFS of Graph", slug: "dfs-of-graph", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1" },
  { group: "Graph", title: "BFS of Graph", slug: "bfs-of-graph", difficulty: "Easy", url: "https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1" },
  { group: "Graph", title: "Detect Cycle in Undirected Graph", slug: "detect-cycle-undirected-graph", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1" },
  { group: "Graph", title: "Detect Cycle in Directed Graph", slug: "detect-cycle-directed-graph", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1" },
  { group: "Graph", title: "Topological Sort", slug: "topological-sort", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/topological-sort/1" },
  { group: "Graph", title: "Number of Islands", slug: "number-of-islands", difficulty: "Medium" },
  { group: "Graph", title: "Is Graph Bipartite", slug: "is-graph-bipartite", difficulty: "Medium" },
  { group: "Graph", title: "Dijkstra's Algorithm", slug: "dijkstra-algorithm", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1" },
  { group: "Graph", title: "Bellman-Ford Algorithm", slug: "bellman-ford", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1" },
  { group: "Graph", title: "Floyd Warshall Algorithm", slug: "floyd-warshall", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1" },
  { group: "Graph", title: "Minimum Spanning Tree (Prim's)", slug: "prims-mst", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
  { group: "Graph", title: "Minimum Spanning Tree (Kruskal's)", slug: "kruskal-mst", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree-using-kruskal/1" },
  { group: "Dynamic Programming", title: "Maximum Product Subarray", slug: "maximum-product-subarray", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Longest Increasing Subsequence", slug: "longest-increasing-subsequence", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Longest Common Subsequence", slug: "longest-common-subsequence", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "0-1 Knapsack", slug: "0-1-knapsack", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1" },
  { group: "Dynamic Programming", title: "Edit Distance", slug: "edit-distance", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Maximum Sum Increasing Subsequence", slug: "maximum-sum-increasing-subsequence", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1" },
  { group: "Dynamic Programming", title: "Matrix Chain Multiplication", slug: "matrix-chain-multiplication", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1" },
  { group: "Dynamic Programming", title: "Maximum Path Sum in Matrix", slug: "maximum-path-sum-in-matrix", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/path-in-matrix3805/1" },
  { group: "Dynamic Programming", title: "Coin Change", slug: "coin-change", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Subset Sum Problem", slug: "subset-sum-problem", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1" },
  { group: "Dynamic Programming", title: "Rod Cutting", slug: "rod-cutting", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/rod-cutting0840/1" },
  { group: "Dynamic Programming", title: "Egg Dropping Puzzle", slug: "super-egg-drop", difficulty: "Hard" },
  { group: "Dynamic Programming", title: "Word Break", slug: "word-break", difficulty: "Medium" },
  { group: "Dynamic Programming", title: "Palindrome Partitioning II (MCM)", slug: "palindrome-partitioning-ii", difficulty: "Hard" },
  { group: "Dynamic Programming", title: "Maximum Profit in Job Scheduling", slug: "maximum-profit-in-job-scheduling", difficulty: "Hard" },
  { group: "Trie", title: "Implement Trie (Prefix Tree)", slug: "implement-trie-prefix-tree", difficulty: "Medium" },
  { group: "Trie", title: "Implement Trie II", slug: "trie-insert-and-search", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/trie-insert-and-search0651/1" },
  { group: "Trie", title: "Longest String with All Prefixes", slug: "complete-string", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/complete-string0937/1" },
  { group: "Trie", title: "Number of Distinct Substrings in a String", slug: "count-distinct-substrings", difficulty: "Hard", url: "https://www.geeksforgeeks.org/problems/count-of-distinct-substrings/1" },
  { group: "Trie", title: "Power Set", slug: "power-set", difficulty: "Medium", url: "https://www.geeksforgeeks.org/problems/power-set4302/1" },
  { group: "Trie", title: "Maximum XOR of Two Numbers in an Array", slug: "maximum-xor-of-two-numbers-in-an-array", difficulty: "Medium" },
  { group: "Trie", title: "Maximum XOR With an Element From Array", slug: "maximum-xor-with-an-element-from-array", difficulty: "Hard" },
]

export const ROADMAPS: Record<string, RoadmapProblem[]> = {
  'Blind 75': BLIND_75,
  'Grind 75': GRIND_75,
  'NeetCode 150': NEETCODE_150,
  'NeetCode 250': NEETCODE_250,
  "Striver's SDE Sheet": STRIVER_SDE,
}

export const ROADMAP_NAMES = Object.keys(ROADMAPS)

/* -------- local progress (manual + auto-detected) -------- */

const key = (r: string) => `leetcity:roadmap:${r.toLowerCase().replace(/\s+/g, '-')}`

export function loadDone(roadmap: string): Set<string> {
  try {
    const raw = localStorage.getItem(key(roadmap))
    return new Set<string>(raw ? JSON.parse(raw) : [])
  } catch {
    return new Set()
  }
}

export function saveDone(roadmap: string, done: Set<string>) {
  try {
    localStorage.setItem(key(roadmap), JSON.stringify([...done]))
  } catch {
    /* ignore */
  }
}
